# MT5 Constants (no dependency on MetaTrader5 package)
# These constants mirror the official MT5 enums

# Trade actions
TRADE_ACTION_DEAL = 1
TRADE_ACTION_PENDING = 2
TRADE_ACTION_SLTP = 3
TRADE_ACTION_MODIFY = 4
TRADE_ACTION_REMOVE = 5
TRADE_ACTION_CLOSE_BY = 6

# Order types
ORDER_TYPE_BUY = 0
ORDER_TYPE_SELL = 1
ORDER_TYPE_BUY_LIMIT = 2
ORDER_TYPE_SELL_LIMIT = 3
ORDER_TYPE_BUY_STOP = 4
ORDER_TYPE_SELL_STOP = 5
ORDER_TYPE_BUY_STOP_LIMIT = 6
ORDER_TYPE_SELL_STOP_LIMIT = 7

# Order time types
ORDER_TIME_GTC = 0
ORDER_TIME_DAY = 1
ORDER_TIME_SPECIFIED = 2
ORDER_TIME_SPECIFIED_DAY = 3

# Order filling types
ORDER_FILLING_FOK = 0
ORDER_FILLING_IOC = 1
ORDER_FILLING_RETURN = 2

# Trade return codes
TRADE_RETCODE_DONE = 10009
TRADE_RETCODE_DONE_PARTIAL = 10010
TRADE_RETCODE_PLACED = 10008
TRADE_RETCODE_PLACED_PARTIAL = 10018
TRADE_RETCODE_CANCELLED = 10017
TRADE_RETCODE_REJECTED = 10035
TRADE_RETCODE_ERROR = 10011
TRADE_RETCODE_TIMEOUT = 10018
TRADE_RETCODE_INVALID_VOLUME = 10014
TRADE_RETCODE_INVALID_PRICE = 10015
TRADE_RETCODE_INVALID_STOPS = 10016
TRADE_RETCODE_TRADE_DISABLED = 10019
TRADE_RETCODE_MARKET_CLOSED = 10020
TRADE_RETCODE_NO_MONEY = 10019
TRADE_RETCODE_PRICE_CHANGED = 10021
TRADE_RETCODE_PRICE_OFF = 10022
TRADE_RETCODE_INVALID_EXPIRATION = 10023
TRADE_RETCODE_ORDER_CHANGED = 10024
TRADE_RETCODE_TOO_MANY_REQUESTS = 10025
TRADE_RETCODE_NO_CHANGES = 10026
TRADE_RETCODE_SERVER_DISABLES_AT = 10027
TRADE_RETCODE_CLIENT_DISABLES_AT = 10028
TRADE_RETCODE_LOCKED = 10029
TRADE_RETCODE_FROZEN = 10030
TRADE_RETCODE_ONLY_LONG = 10031
TRADE_RETCODE_ONLY_SHORT = 10032
