FROM python:3.11-slim
WORKDIR /app
COPY services/backend_admin/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY services/common ./common
COPY services/backend_admin/. .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
